version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch
      - redis
    environment:
      - DATABASE_URL=postgresql://kanadshield:password@postgres/kanadshield
      - ES_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=kanadshield-secret-key-change-in-prod
    volumes:
      - ./pcap_storage:/app/pcap_storage
      - ./backend:/app
    cap_add:
      - NET_ADMIN
      - NET_RAW

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kanadshield
      POSTGRES_USER: kanadshield
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
  esdata:
